### ISSUE TITLE
Piping does not work properly

### ISSUE THREAD

**Issue by vrilly** [toni-schmitt/minishell#50]
**Describe the bug**
When piping between processes, not more than 64KiB can be sent over the pipe

**To Reproduce**

Execute `dd if=/dev/urandom | pv | dd of=/dev/null`
The program locks up because write call is blocking, when pressing CTRL+C to send a SIGINT the exit messages of dd and pv show that only 65536 bytes are sent. The problem is also reproducable without pv(pipe viewer) by just executing the 2 dd instances.

**Expected behavior**
The pipes writing to eachother without it blocking or getting limited to 64KiB

**Comment by tblaase** [comment]
"Mac OS X, for example, uses a capacity of 16384 bytes by default, but can switch to 65336 byte capacities if large write are made to the pipe, or will switch to a capacity of a single system page if too much kernel memory is already being used by pipe buffers (see [xnu/bsd/sys/pipe.h](http://www.opensource.apple.com/source/xnu/xnu-1504.9.37/bsd/sys/pipe.h), and [xnu/bsd/kern/sys_pipe.c](http://www.opensource.apple.com/source/xnu/xnu-1504.9.37/bsd/kern/sys_pipe.c); since these are from FreeBSD, the same behavior may happen there, too)." (Source: https://unix.stackexchange.com/questions/11946/how-big-is-the-pipe-buffer)

So it will not be fixed or fixable with the way pipes work right now in our minishell and on macOS.
Bash probably handles pipes not by creating an actual pipe like we do, it will most likely create some temporary file where the output of the pipe is stored.
